import {StyleSheet} from 'react-native';
import {colors} from '../../theme/colors';

export const styles = StyleSheet.create({
  productContainer: {
    shadowColor: colors.black,
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 5,
    backgroundColor: 'white',
    flex: 1,
    borderRadius: 20,
    margin: 7,
    padding: 10,
    gap: 12,
  },
  mainContainer: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 30,
  },
  productImage: {
    height: 100,
    width: 100,
    resizeMode: 'center',
    alignSelf: 'center',
  },
  title: {
    textAlign: 'center',
    fontSize: 12,
    fontWeight: '500',
    color: colors.black,
    bottom: 5,
  },
  divider: {
    width: 120,
    borderWidth: 0.4,
    borderColor: colors.black,
    alignSelf: 'center',
  },
  price: {
    color: colors.black,
    left: 10,
    fontSize: 15,
    fontWeight: '600',
    position: 'absolute',
    bottom: 5,
  },
  addProductButton: {
    backgroundColor: colors.darkGray,
    width: 60,
    height: 60,
    position: 'absolute',
    bottom: 20,
    left: '78%',
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addProductIcon: {width: 30, height: 30, resizeMode: 'center'},
  modalBackground: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '100%',
    gap: 20,
    padding: 30,
    backgroundColor: colors.white,
    borderRadius: 10,
  },
  inputStyle: {
    borderBottomWidth: 1,
    borderColor: colors.black,
    paddingLeft: 10,
    color: colors.black,
  },
  SelectedProductImage: {
    height: 150,
    width: 150,
    resizeMode: 'center',
    alignSelf: 'center',
  },
  SelectedProductTitle: {
    fontSize: 18,
    textAlign: 'center',
    fontWeight: '700',
    color: colors.black,
  },
  SelectedProductPrice: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.black,
  },
  SelectedProductDescription: {},
  SelectedProductCategory: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.black,
    textAlign: 'center',
  },
  deleteProductImage: {
    height: 70,
    width: 50,
    resizeMode: 'center',
  },
  openEndModalContanier: {
    backgroundColor: colors.white,
    padding: 20,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  deleteProductButton: {
    shadowColor: colors.black,
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 5,
    backgroundColor: colors.darkGray,
    height: 30,
    width: '35%',
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deteleProductText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '600',
  },
  updateProductButton: {
    shadowColor: colors.black,
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 5,
    backgroundColor: colors.lightGray,
    height: 30,
    width: '35%',
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  grayButton: {
    shadowColor: colors.black,
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 5,
    backgroundColor: colors.darkGray,
    borderRadius: 8,
    height: 40,
    justifyContent: 'center',
    alignContent: 'center',
  },
  lightGrayButton: {
    shadowColor: colors.black,
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 5,
    backgroundColor: colors.lightGray,
    borderRadius: 8,
    height: 40,
    justifyContent: 'center',
    alignContent: 'center',
  },
  loadingContainer: {
    // flex: 1,
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  newProductAddText: {
    textAlign: 'center',
    color: colors.black,
    fontSize: 20,
    fontWeight: '700',
  },
  text: {
    color: colors.black,
    textAlign: 'center',
  },
  dotStyle: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.white,
  },
  moreTextView: {
    height: 30,
    justifyContent: 'center',
  },
  moreProductText: {
    fontSize: 20,
    fontWeight: '700',
    paddingHorizontal: 20,
  },
  ratingStarContainer: {
    paddingHorizontal: 80,
    gap: 10,
  },
  posterImage: {
    width: '100%',
    height: 230,
  },
});
